### ISSUE TITLE
support disabling the mass storage function at runtime

### ISSUE THREAD

**Issue by chombourger** [siemens/mtda#214]
Some devices do not allow the boot media to be configured and will instead check if a (valid) USB stick is connected before booting the system. We may need a disable() function to get the mass storage function removed from the USBF stack

**Comment by badrikeshp-mg** [comment]
Hi @chombourger , is this issue related to:
1. That is currently faced on older comfort boards, where the shared storage gets detected on the target even when it attached to host. And the disable function will help so that shared storage won't get detected on target side
2. Or any new enhancement for new comfort hmi boards that can help in bypassing maintenance key press to boot to service stick

**Comment by chombourger** [comment]
> Hi @chombourger , is this issue related to:
> 
> 1. That is currently faced on older comfort boards, where the shared storage gets detected on the target even when it attached to host. And the disable function will help so that shared storage won't get detected on target side
> 2. Or any new enhancement for new comfort hmi boards that can help in bypassing maintenance key press to boot to service stick

This is about (1)
